export const items = [
  { name: "Billy Butcher", link: "/characters/billy-butcher" },
  { name: "Hughie Campbell", link: "/characters/hughie-campbell" },
  { name: "Starlight", link: "/characters/starlight" },
  { name: "Mother's Milk", link: "/characters/mothers-milk" },
  { name: "Frenchie", link: "/characters/frenchie" },
  { name: "Kimiko Miyashiro", link: "/characters/kimiko-miyashiro" },
  { name: "Ryan Butcher", link: "/characters/ryan-butcher" },
  { name: "Homelander", link: "/characters/homelander" },
  { name: "Stormfront", link: "/characters/stormfront" },
  { name: "Oh Father", link: "/characters/oh-father" },
  { name: "Black Noir I", link: "/characters/black-noir-one" },
  { name: "Black Noir II", link: "/characters/black-noir-two" },
  { name: "The Deep", link: "/characters/the-deep" },
  { name: "A-Train", link: "/characters/a-train" },
  { name: "Soldier Boy", link: "/characters/soldier-boy" },
  { name: "Queen Mauve", link: "/characters/queen-mauve" },
  { name: "Firecracker", link: "/characters/firecracker" },
  { name: "Stan Edgar", link: "/characters/stan-edgar" },
  { name: "Victoria Neuman", link: "/characters/victoria-neuman" },
  { name: "Marie Moreau", link: "/characters/marie-moreau" },
  { name: "Ashley Barrett", link: "/characters/ashley-barrett" },
  { name: "Dr.Thomas R. Godolkin", link: "/characters/thomas-godolkin" },
];
