export const items = [
  { name: "Billy Butcher", link: "/billy-butcher" },
  { name: "Hughie Campbell", link: "/hughie-campbell" },
  { name: "Starlight", link: "/starlight" },
  { name: "Mother's Milk", link: "/mothers-milk" },
  { name: "Frenchie", link: "/frenchie" },
  { name: "Kimiko Miyashiro", link: "/kimiko-miyashiro" },
  { name: "Ryan Butcher", link: "/ryan-butcher" },
  { name: "Homelander", link: "/homelander" },
  { name: "Stormfront", link: "/stormfront" },
  { name: "Oh Father", link: "/oh-father" },
  { name: "Black Noir I", link: "/black-noir-one" },
  { name: "Black Noir II", link: "/black-noir-two" },
  { name: "The Deep", link: "/the-deep" },
  { name: "A-Train", link: "/a-train" },
  { name: "Soldier Boy", link: "/soldier-boy" },
  { name: "Queen Mauve", link: "/queen-mauve" },
  { name: "Firecracker", link: "/firecracker" },
  { name: "Stan Edgar", link: "/stan-edgar" },
  { name: "Victoria Neuman", link: "/victoria-neuman" },
  { name: "Marie Moreau", link: "/marie-moreau" },
  { name: "Ashley Barrett", link: "/ashley-barrett" },
  { name: "Dr.Thomas R. Godolkin", link: "/thomas-godolkin" },
];
